export const PHASES = {
  FINGER: 'FINGER',
  SHOCK: 'SHOCK',
  SAW: 'SAW',
};

export const PHASE_CONFIG = {
  FINGER: {
    label: 'Finger Phase',
    description: 'Lose and Lucas chops off your fingers...',
    rounds: 3,
    baseBet: 1,
    hasTrumps: false,
    color: '#8b0000',
  },
  SHOCK: {
    label: 'Shock Phase',
    description: 'Lose and you get electrocuted. The voltage increases each round.',
    rounds: 3,
    baseBet: 1,
    hasTrumps: true,
    color: '#1a3a8b',
  },
  SAW: {
    label: 'Saw Phase',
    description: 'The saw inches closer. One wrong move and it\'s all over.',
    rounds: 3,
    baseBet: 2,
    hasTrumps: true,
    color: '#4a1a00',
  },
};

export const TRUMP_TYPES = {
  // Permanent on-table effects
  ONE_UP: 'ONE_UP',
  TWO_UP: 'TWO_UP',
  TWO_UP_PLUS: 'TWO_UP_PLUS',
  SHIELD: 'SHIELD',
  SHIELD_PLUS: 'SHIELD_PLUS',
  DESTROY: 'DESTROY',
  DESTROY_PLUS: 'DESTROY_PLUS',
  DESTROY_PLUS_PLUS: 'DESTROY_PLUS_PLUS',
  GO_FOR_17: 'GO_FOR_17',
  GO_FOR_24: 'GO_FOR_24',
  GO_FOR_27: 'GO_FOR_27',
  HARVEST: 'HARVEST',
  DESIRE: 'DESIRE',
  DESIRE_PLUS: 'DESIRE_PLUS',
  MIND_SHIFT: 'MIND_SHIFT',
  MIND_SHIFT_PLUS: 'MIND_SHIFT_PLUS',
  CONJURE: 'CONJURE',
  BLACK_MAGIC: 'BLACK_MAGIC',
  ESCAPE: 'ESCAPE',
  TWENTY_ONE_UP: 'TWENTY_ONE_UP',
  OBLIVION: 'OBLIVION',
  DEAD_SILENCE: 'DEAD_SILENCE',
  DESPERATION: 'DESPERATION',
  HAPPINESS: 'HAPPINESS',

  // Instant-effect cards
  CARD_2: 'CARD_2',
  CARD_3: 'CARD_3',
  CARD_4: 'CARD_4',
  CARD_5: 'CARD_5',
  CARD_6: 'CARD_6',
  CARD_7: 'CARD_7',
  REMOVE: 'REMOVE',
  RETURN: 'RETURN',
  EXCHANGE: 'EXCHANGE',
  TRUMP_SWITCH: 'TRUMP_SWITCH',
  TRUMP_SWITCH_PLUS: 'TRUMP_SWITCH_PLUS',
  PERFECT_DRAW: 'PERFECT_DRAW',
  PERFECT_DRAW_PLUS: 'PERFECT_DRAW_PLUS',
  ULTIMATE_DRAW: 'ULTIMATE_DRAW',
  CURSE: 'CURSE',
  LOVE_YOUR_ENEMY: 'LOVE_YOUR_ENEMY',
  SHIELD_ASSAULT: 'SHIELD_ASSAULT',
  SHIELD_ASSAULT_PLUS: 'SHIELD_ASSAULT_PLUS',
};

// Which trumps are permanent (stay on table) vs instant (one-time effect)
export const PERMANENT_TRUMPS = new Set([
  TRUMP_TYPES.ONE_UP,
  TRUMP_TYPES.TWO_UP,
  TRUMP_TYPES.TWO_UP_PLUS,
  TRUMP_TYPES.SHIELD,
  TRUMP_TYPES.SHIELD_PLUS,
  TRUMP_TYPES.DESTROY,
  TRUMP_TYPES.DESTROY_PLUS,
  TRUMP_TYPES.DESTROY_PLUS_PLUS,
  TRUMP_TYPES.GO_FOR_17,
  TRUMP_TYPES.GO_FOR_24,
  TRUMP_TYPES.GO_FOR_27,
  TRUMP_TYPES.HARVEST,
  TRUMP_TYPES.DESIRE,
  TRUMP_TYPES.DESIRE_PLUS,
  TRUMP_TYPES.MIND_SHIFT,
  TRUMP_TYPES.MIND_SHIFT_PLUS,
  TRUMP_TYPES.CONJURE,
  TRUMP_TYPES.BLACK_MAGIC,
  TRUMP_TYPES.ESCAPE,
  TRUMP_TYPES.TWENTY_ONE_UP,
  TRUMP_TYPES.OBLIVION,
  TRUMP_TYPES.DEAD_SILENCE,
  TRUMP_TYPES.DESPERATION,
  TRUMP_TYPES.HAPPINESS,
]);

export const MAX_TABLE_TRUMPS = 5;

export const TRUMP_DEFINITIONS = {
  [TRUMP_TYPES.ONE_UP]: {
    name: 'One-Up',
    description: "Opponent's bet increases by 1 while on table. Draw 1 trump.",
    permanent: true,
    color: '#c0392b',
    icon: '⬆',
  },
  [TRUMP_TYPES.TWO_UP]: {
    name: 'Two-Up',
    description: "Opponent's bet increases by 2 while on table. Draw 1 trump.",
    permanent: true,
    color: '#c0392b',
    icon: '⬆⬆',
  },
  [TRUMP_TYPES.TWO_UP_PLUS]: {
    name: 'Two-Up+',
    description: "Return opponent's last face-up card to deck. Opponent's bet +2.",
    permanent: true,
    color: '#922b21',
    icon: '⬆⬆+',
  },
  [TRUMP_TYPES.SHIELD]: {
    name: 'Shield',
    description: 'Your bet is reduced by 1 while on table.',
    permanent: true,
    color: '#1a5276',
    icon: '🛡',
  },
  [TRUMP_TYPES.SHIELD_PLUS]: {
    name: 'Shield+',
    description: 'Your bet is reduced by 2 while on table.',
    permanent: true,
    color: '#154360',
    icon: '🛡+',
  },
  [TRUMP_TYPES.DESTROY]: {
    name: 'Destroy',
    description: "Remove the last trump card your opponent placed on the table.",
    permanent: true,
    color: '#6e2f1a',
    icon: '💥',
  },
  [TRUMP_TYPES.DESTROY_PLUS]: {
    name: 'Destroy+',
    description: "Remove all of opponent's trump cards from table.",
    permanent: true,
    color: '#6e2f1a',
    icon: '💥+',
  },
  [TRUMP_TYPES.DESTROY_PLUS_PLUS]: {
    name: 'Destroy++',
    description: "Remove all opponent's trumps. Opponent cannot use trumps this round.",
    permanent: true,
    color: '#4a1a00',
    icon: '💥++',
  },
  [TRUMP_TYPES.GO_FOR_17]: {
    name: 'Go for 17',
    description: 'Closest to 17 wins. Replaces other Go For cards.',
    permanent: true,
    color: '#7d6608',
    icon: '17',
  },
  [TRUMP_TYPES.GO_FOR_24]: {
    name: 'Go for 24',
    description: 'Closest to 24 wins. Replaces other Go For cards.',
    permanent: true,
    color: '#7d6608',
    icon: '24',
  },
  [TRUMP_TYPES.GO_FOR_27]: {
    name: 'Go for 27',
    description: 'Closest to 27 wins. Replaces other Go For cards.',
    permanent: true,
    color: '#7d6608',
    icon: '27',
  },
  [TRUMP_TYPES.HARVEST]: {
    name: 'Harvest',
    description: 'Draw a trump after every trump use while on table.',
    permanent: true,
    color: '#1d8348',
    icon: '🌾',
  },
  [TRUMP_TYPES.DESIRE]: {
    name: 'Desire',
    description: "Opponent's bet raised by half their trump cards held.",
    permanent: true,
    color: '#6c3483',
    icon: '🖤',
  },
  [TRUMP_TYPES.DESIRE_PLUS]: {
    name: 'Desire+',
    description: "Opponent's bet raised by number of trump cards they hold.",
    permanent: true,
    color: '#512e5f',
    icon: '🖤+',
  },
  [TRUMP_TYPES.MIND_SHIFT]: {
    name: 'Mind Shift',
    description: "Opponent loses half their trumps at end of round (removed if they use 2 trumps in one turn).",
    permanent: true,
    color: '#1a5276',
    icon: '🧠',
  },
  [TRUMP_TYPES.MIND_SHIFT_PLUS]: {
    name: 'Mind Shift+',
    description: "Opponent loses all trumps at end of round (removed if they use 3 in one turn).",
    permanent: true,
    color: '#154360',
    icon: '🧠+',
  },
  [TRUMP_TYPES.CONJURE]: {
    name: 'Conjure',
    description: 'Draw three trump cards. Your bet +1 while on table.',
    permanent: true,
    color: '#6c3483',
    icon: '✨',
  },
  [TRUMP_TYPES.BLACK_MAGIC]: {
    name: 'Black Magic',
    description: "Discard half your trumps, draw best number card. Opponent's bet +10.",
    permanent: true,
    color: '#1c1c1c',
    icon: '🔮',
  },
  [TRUMP_TYPES.ESCAPE]: {
    name: 'Escape',
    description: 'If still on table at end of round, you escape (auto-win).',
    permanent: true,
    color: '#1d8348',
    icon: '🏃',
  },
  [TRUMP_TYPES.TWENTY_ONE_UP]: {
    name: 'Twenty-One-Up',
    description: "If your total is 21, opponent's bet raised by 21.",
    permanent: true,
    color: '#c0392b',
    icon: '21↑',
  },
  [TRUMP_TYPES.OBLIVION]: {
    name: 'Oblivion',
    description: 'Cancels this round and begins a new round.',
    permanent: true,
    color: '#1c2833',
    icon: '∅',
  },
  [TRUMP_TYPES.DEAD_SILENCE]: {
    name: 'Dead Silence',
    description: 'Opponent cannot draw cards (even via trump effects) while on table.',
    permanent: true,
    color: '#1c2833',
    icon: '🤫',
  },
  [TRUMP_TYPES.DESPERATION]: {
    name: 'Desperation',
    description: "Both bets +100. Opponent cannot draw. Best hand wins.",
    permanent: true,
    color: '#1a0000',
    icon: '☠',
  },
  [TRUMP_TYPES.HAPPINESS]: {
    name: 'Happiness',
    description: 'Both players draw one trump card.',
    permanent: true,
    color: '#d4ac0d',
    icon: '😊',
  },
  [TRUMP_TYPES.CARD_2]: {
    name: '2 Card',
    description: 'Draw the 2 card from the deck.',
    permanent: false,
    color: '#2e86c1',
    icon: '2',
  },
  [TRUMP_TYPES.CARD_3]: {
    name: '3 Card',
    description: 'Draw the 3 card from the deck.',
    permanent: false,
    color: '#2e86c1',
    icon: '3',
  },
  [TRUMP_TYPES.CARD_4]: {
    name: '4 Card',
    description: 'Draw the 4 card from the deck.',
    permanent: false,
    color: '#2e86c1',
    icon: '4',
  },
  [TRUMP_TYPES.CARD_5]: {
    name: '5 Card',
    description: 'Draw the 5 card from the deck.',
    permanent: false,
    color: '#2e86c1',
    icon: '5',
  },
  [TRUMP_TYPES.CARD_6]: {
    name: '6 Card',
    description: 'Draw the 6 card from the deck.',
    permanent: false,
    color: '#2e86c1',
    icon: '6',
  },
  [TRUMP_TYPES.CARD_7]: {
    name: '7 Card',
    description: 'Draw the 7 card from the deck.',
    permanent: false,
    color: '#2e86c1',
    icon: '7',
  },
  [TRUMP_TYPES.REMOVE]: {
    name: 'Remove',
    description: "Return opponent's last face-up card to the deck.",
    permanent: false,
    color: '#e74c3c',
    icon: '✖',
  },
  [TRUMP_TYPES.RETURN]: {
    name: 'Return',
    description: 'Return your last face-up card to the deck.',
    permanent: false,
    color: '#27ae60',
    icon: '↩',
  },
  [TRUMP_TYPES.EXCHANGE]: {
    name: 'Exchange',
    description: 'Swap last cards drawn by you and opponent (no face-down swaps).',
    permanent: false,
    color: '#8e44ad',
    icon: '⇄',
  },
  [TRUMP_TYPES.TRUMP_SWITCH]: {
    name: 'Trump Switch',
    description: 'Discard 2 random trumps, draw 3 new ones.',
    permanent: false,
    color: '#d35400',
    icon: '🔄',
  },
  [TRUMP_TYPES.TRUMP_SWITCH_PLUS]: {
    name: 'Trump Switch+',
    description: 'Discard 1 random trump, draw 4 new ones.',
    permanent: false,
    color: '#ca6f1e',
    icon: '🔄+',
  },
  [TRUMP_TYPES.PERFECT_DRAW]: {
    name: 'Perfect Draw',
    description: 'Draw the best possible card from the deck.',
    permanent: false,
    color: '#f1c40f',
    icon: '⭐',
  },
  [TRUMP_TYPES.PERFECT_DRAW_PLUS]: {
    name: 'Perfect Draw+',
    description: "Draw best card. Opponent's bet +5 while on table.",
    permanent: false,
    color: '#d4ac0d',
    icon: '⭐+',
  },
  [TRUMP_TYPES.ULTIMATE_DRAW]: {
    name: 'Ultimate Draw',
    description: 'Draw best card. Also draw two trump cards.',
    permanent: false,
    color: '#f39c12',
    icon: '⭐⭐',
  },
  [TRUMP_TYPES.CURSE]: {
    name: 'Curse',
    description: 'Discard 1 random trump. Force opponent to draw the highest card from deck.',
    permanent: false,
    color: '#6c3483',
    icon: '💀',
  },
  [TRUMP_TYPES.LOVE_YOUR_ENEMY]: {
    name: 'Love Your Enemy',
    description: 'Opponent draws the best possible card for them.',
    permanent: false,
    color: '#c0392b',
    icon: '❤',
  },
  [TRUMP_TYPES.SHIELD_ASSAULT]: {
    name: 'Shield Assault',
    description: "Remove 3 Shield-type cards from your side. Opponent's bet +3.",
    permanent: false,
    color: '#6e2f1a',
    icon: '🛡💥',
  },
  [TRUMP_TYPES.SHIELD_ASSAULT_PLUS]: {
    name: 'Shield Assault+',
    description: "Remove 2 Shield-type cards from your side. Opponent's bet +5.",
    permanent: false,
    color: '#4a1a00',
    icon: '🛡💥+',
  },
};

// Trump weight table — controls drop rate per phase.
// Weight 10 = normal. 0 = never. Relative: a card with weight 20 is 2× more likely than weight 10.
// Powerful/broken cards are locked to SAW only with low weight (1-2 out of ~100+ total pool weight).
export const TRUMP_WEIGHTS = {
  // ── Broken / game-ending ────────────────────────────────
  // ESCAPE: auto-wins the round if still on table at resolution
  [TRUMP_TYPES.ESCAPE]:             { FINGER: 0, SHOCK: 0, SAW: 1 },
  // DESPERATION: both bets +100 AND opponent can't draw — insta-win combo
  [TRUMP_TYPES.DESPERATION]:       { FINGER: 0, SHOCK: 0, SAW: 1 },
  // BLACK_MAGIC: draw best card + opponent bet +10
  [TRUMP_TYPES.BLACK_MAGIC]:       { FINGER: 0, SHOCK: 0, SAW: 2 },
  // TWENTY_ONE_UP: opponent bet +21 on a natural 21 — one-shot potential
  [TRUMP_TYPES.TWENTY_ONE_UP]:     { FINGER: 0, SHOCK: 0, SAW: 2 },
  // DEAD_SILENCE: opponent literally cannot draw any card
  [TRUMP_TYPES.DEAD_SILENCE]:      { FINGER: 0, SHOCK: 0, SAW: 3 },
  // DESTROY++: wipes all opponent trumps + blocks trump use for the round
  [TRUMP_TYPES.DESTROY_PLUS_PLUS]: { FINGER: 0, SHOCK: 0, SAW: 3 },
  // MIND_SHIFT+: opponent loses ALL trumps at end of round
  [TRUMP_TYPES.MIND_SHIFT_PLUS]:   { FINGER: 0, SHOCK: 0, SAW: 3 },
  // OBLIVION: cancels the round — tempo tool that erases opponent progress
  [TRUMP_TYPES.OBLIVION]:          { FINGER: 0, SHOCK: 0, SAW: 4 },
  // ULTIMATE_DRAW: best card + draw 2 more trumps — snowball machine
  [TRUMP_TYPES.ULTIMATE_DRAW]:     { FINGER: 0, SHOCK: 0, SAW: 4 },

  // ── Strong but fair in later game ───────────────────────
  [TRUMP_TYPES.DESTROY_PLUS]:      { FINGER: 0, SHOCK: 3,  SAW: 8 },
  [TRUMP_TYPES.MIND_SHIFT]:        { FINGER: 0, SHOCK: 4,  SAW: 8 },
  [TRUMP_TYPES.DESIRE_PLUS]:       { FINGER: 0, SHOCK: 4,  SAW: 8 },
  [TRUMP_TYPES.TWO_UP_PLUS]:       { FINGER: 0, SHOCK: 5,  SAW: 10 },
  [TRUMP_TYPES.PERFECT_DRAW_PLUS]: { FINGER: 0, SHOCK: 5,  SAW: 10 },
  [TRUMP_TYPES.TRUMP_SWITCH_PLUS]: { FINGER: 0, SHOCK: 5,  SAW: 10 },
  [TRUMP_TYPES.SHIELD_PLUS]:       { FINGER: 0, SHOCK: 5,  SAW: 10 },
  [TRUMP_TYPES.CONJURE]:           { FINGER: 0, SHOCK: 5,  SAW: 8 },
  [TRUMP_TYPES.SHIELD_ASSAULT_PLUS]:{ FINGER: 0, SHOCK: 6, SAW: 10 },

  // ── Normal cards — appear in both SHOCK and SAW ─────────
  [TRUMP_TYPES.ONE_UP]:            { FINGER: 0, SHOCK: 10, SAW: 10 },
  [TRUMP_TYPES.TWO_UP]:            { FINGER: 0, SHOCK: 10, SAW: 10 },
  [TRUMP_TYPES.SHIELD]:            { FINGER: 0, SHOCK: 10, SAW: 10 },
  [TRUMP_TYPES.DESTROY]:           { FINGER: 0, SHOCK: 10, SAW: 10 },
  [TRUMP_TYPES.GO_FOR_17]:         { FINGER: 0, SHOCK: 8,  SAW: 8 },
  [TRUMP_TYPES.GO_FOR_24]:         { FINGER: 0, SHOCK: 8,  SAW: 8 },
  [TRUMP_TYPES.GO_FOR_27]:         { FINGER: 0, SHOCK: 6,  SAW: 8 },
  [TRUMP_TYPES.HARVEST]:           { FINGER: 0, SHOCK: 8,  SAW: 8 },
  [TRUMP_TYPES.DESIRE]:            { FINGER: 0, SHOCK: 8,  SAW: 10 },
  [TRUMP_TYPES.HAPPINESS]:         { FINGER: 0, SHOCK: 10, SAW: 10 },
  [TRUMP_TYPES.CARD_2]:            { FINGER: 0, SHOCK: 10, SAW: 8 },
  [TRUMP_TYPES.CARD_3]:            { FINGER: 0, SHOCK: 10, SAW: 8 },
  [TRUMP_TYPES.CARD_4]:            { FINGER: 0, SHOCK: 10, SAW: 8 },
  [TRUMP_TYPES.CARD_5]:            { FINGER: 0, SHOCK: 10, SAW: 8 },
  [TRUMP_TYPES.CARD_6]:            { FINGER: 0, SHOCK: 10, SAW: 8 },
  [TRUMP_TYPES.CARD_7]:            { FINGER: 0, SHOCK: 6,  SAW: 6 },
  [TRUMP_TYPES.REMOVE]:            { FINGER: 0, SHOCK: 10, SAW: 10 },
  [TRUMP_TYPES.RETURN]:            { FINGER: 0, SHOCK: 10, SAW: 10 },
  [TRUMP_TYPES.EXCHANGE]:          { FINGER: 0, SHOCK: 8,  SAW: 8 },
  [TRUMP_TYPES.TRUMP_SWITCH]:      { FINGER: 0, SHOCK: 8,  SAW: 8 },
  [TRUMP_TYPES.PERFECT_DRAW]:      { FINGER: 0, SHOCK: 10, SAW: 10 },
  [TRUMP_TYPES.CURSE]:             { FINGER: 0, SHOCK: 4,  SAW: 6 },
  [TRUMP_TYPES.LOVE_YOUR_ENEMY]:   { FINGER: 0, SHOCK: 6,  SAW: 6 },
  [TRUMP_TYPES.SHIELD_ASSAULT]:    { FINGER: 0, SHOCK: 6,  SAW: 8 },
};

// Player-accessible trumps (not enemy-exclusive)
export const PLAYER_TRUMP_POOL = [
  TRUMP_TYPES.ONE_UP,
  TRUMP_TYPES.TWO_UP,
  TRUMP_TYPES.SHIELD,
  TRUMP_TYPES.CARD_2,
  TRUMP_TYPES.CARD_3,
  TRUMP_TYPES.CARD_4,
  TRUMP_TYPES.CARD_5,
  TRUMP_TYPES.CARD_6,
  TRUMP_TYPES.CARD_7,
  TRUMP_TYPES.REMOVE,
  TRUMP_TYPES.RETURN,
  TRUMP_TYPES.TRUMP_SWITCH,
  TRUMP_TYPES.PERFECT_DRAW,
  TRUMP_TYPES.GO_FOR_17,
  TRUMP_TYPES.GO_FOR_24,
  // Advanced — SAW-only or low-weight on SHOCK
  TRUMP_TYPES.ESCAPE,
  TRUMP_TYPES.TWENTY_ONE_UP,
  TRUMP_TYPES.DEAD_SILENCE,
  TRUMP_TYPES.DESTROY,
  TRUMP_TYPES.DESTROY_PLUS,
  TRUMP_TYPES.DESTROY_PLUS_PLUS,
  TRUMP_TYPES.PERFECT_DRAW_PLUS,
  TRUMP_TYPES.ULTIMATE_DRAW,
  TRUMP_TYPES.OBLIVION,
  TRUMP_TYPES.SHIELD_PLUS,
  TRUMP_TYPES.MIND_SHIFT,
  TRUMP_TYPES.MIND_SHIFT_PLUS,
  TRUMP_TYPES.CONJURE,
  TRUMP_TYPES.BLACK_MAGIC,
];

// Enemy bot trump pool
export const BOT_TRUMP_POOL = [
  TRUMP_TYPES.ONE_UP,
  TRUMP_TYPES.TWO_UP,
  TRUMP_TYPES.SHIELD,
  TRUMP_TYPES.REMOVE,
  TRUMP_TYPES.CARD_3,
  TRUMP_TYPES.CARD_5,
  TRUMP_TYPES.CARD_6,
  TRUMP_TYPES.PERFECT_DRAW,
  TRUMP_TYPES.GO_FOR_24,
  TRUMP_TYPES.CURSE,
  TRUMP_TYPES.DESPERATION,
  TRUMP_TYPES.DESIRE,
  TRUMP_TYPES.MIND_SHIFT,
  TRUMP_TYPES.HAPPINESS,
  // Advanced — SAW-only or low-weight on SHOCK
  TRUMP_TYPES.ESCAPE,
  TRUMP_TYPES.DEAD_SILENCE,
  TRUMP_TYPES.DESTROY_PLUS,
  TRUMP_TYPES.DESTROY_PLUS_PLUS,
  TRUMP_TYPES.MIND_SHIFT_PLUS,
  TRUMP_TYPES.OBLIVION,
  TRUMP_TYPES.TWENTY_ONE_UP,
  TRUMP_TYPES.BLACK_MAGIC,
];
